apiVersion: v1
kind: Secret
metadata:
  namespace: {{ default "default" .Values.global.namespace | quote }}
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if and .Values.secrets .Values.secrets.erlangCookie -}}
  erlang-cookie: {{ .Values.secrets.erlangCookie | b64enc | quote }}
  {{- else -}}
  erlang-cookie: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end -}}
  {{- if and .Values.secrets .Values.secrets.encryptionSecretKey -}}
  secret-key: {{ .Values.secrets.encryptionSecretKey | b64enc | quote }}
  {{- else -}}
  secret-key: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end -}}
