apiVersion: v1
kind: Service
metadata:
  namespace: {{ default "default" .Values.global.namespace | quote }}
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: internal-port
    protocol: TCP
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  selector:
    app: {{ .Values.applicationName }}
